config/routes.rb
Flipbook::Application.routes.draw do
  
  resources :posts
  resources :pages
  resources :sessions
  
  root :to => "posts#index"
  
  match '/create',  :to =>  "posts#create"
  match 'contact' => 'pages#new', :as => 'contact', :via => :get
  match 'contact' => 'pages#create', :as => 'contact', :via => :post
  match '/about',   :to => 'pages#about'
  
  match '/login'  => 'sessions#new',     :as => :login
  match '/feed',  :to =>  'posts#feed'
  match '/logout' => 'sessions#destroy', :as => :logout
  
 
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  
  include Paperclip::Glue
  belongs_to(:user)
  attr_accessible :title, :desc, :img
  
  has_attached_file :img, :styles => { :large => "800x600>" ,:medium => "100x100", :thumb => "50x50" }
  
  validates_attachment_presence :img
  validates :title, :presence => true 
  validates :desc, :presence => true 


end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible(:first_name, :last_name, :email, 
                  :password, :password_confirmation)
  
  validates(:first_name, :presence => true)
  validates(:last_name,  :presence => true)
  validates(:email,      :presence => true, :format => /^.+@.+/)
  has_secure_password
  has_many(:posts)
  
  def self.clean_email (email)
    email.to_s.strip.downcase
  end
  

  def self.authenticate (email, clear_text_password)
    find_by_email(clean_email(email)).try(:authenticate, clear_text_password)
  end
  
  ##############################################################################
  private

  before_validation do
    
    self.email = self.class.clean_email(email)

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private
  

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.blank?
  end

  helper_method(:current_user, :logged_in?)
  

  def require_authentication
    redirect_to(login_path) unless logged_in?
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
     @title = "Home"
   end

   def create
     @title = "Contact"
      
      @message = Message.new(params[:message])

      if @message.valid?
          NotificationsMailer.new_message(@message).deliver
          redirect_to(root_path, :notice => "Message was successfully sent.")
      else
          flash.now.alert = "Please fill all fields."
          render 'new'
      end
  end

   def new
     @title = "About"
     @message = Message.new
   end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_filter(:require_authentication, :only => [:feed,:create,:edit])
  
  def index
    @post = Post.all(:order => "created_at DESC")
    
  end
  
  def feed
    @post = Post.all
    
  end
  
  def create
    @post = Post.create(params[:post])
    
    if @post.save
      redirect_to root_path
    end
  end
  
  def edit
     @post= Post.find(params[:id])
  end
  
  def show
     @post = Post.find(params[:id])
  end
  
  def destroy 
    @post = Post.find(params[:id])
    @post.delete
    respond_to do |format|
      format.html{redirect_to root_path,  notice: 'Post was successfully updated.' }
      format.json { head :no_content }
    end
  end
  
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  skip_filter(:require_authentication)

  def index
    redirect_to(root_path)
  end
  
  def new
  end

  def create
    email, password = params[:user][:email], params[:user][:password]
    
    if user = User.authenticate(email, password)
      session[:user_id] = user.id
      redirect_to( feed_path, :notice => %Q[Welcome, #{user.first_name} #{user.last_name}])
    else
      flash.now.alert = 'Invalid email address or password'
      render('new') # render new.html.erb
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to(root_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  
  def wrap(content)
    sanitize(raw(content.split.map{ |s| wrap_long_string(s) }.join(' ')))
  end

  private

  def wrap_long_string(text, max_width = 10)
    zero_width_space = "&#8203;"
    regex = /.{1,#{max_width}}/
    (text.length < max_width) ? text : 
                                text.scan(regex).join(zero_width_space)
  end
    
    
end

app/helpers/posts_helper.rb
module PostsHelper
  def wrap(content)
    sanitize(raw(content.split.map{ |s| wrap_long_string(s) }.join(' ')))
  end

  private

    def wrap_long_string(text, max_width = 30)
      zero_width_space = "&#8203;"
      regex = /.{1,#{max_width}}/
      (text.length < max_width) ? text : 
                                  text.scan(regex).join(zero_width_space)
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flipbook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href="css/bootstrap.min.css" rel="stylesheet" media="screen">
  <script src="js/bootstrap.js"></script>
  <script src="js/bootstrap.min.js"></script>
  <script src="js/jquery.js"></script>
</head>
<body>
<div class="container">
	<div class='span6'>
	<ul id="nav">
		<li><%= link_to "Home", root_path %></li>
    	<li><%= link_to "About", about_path%></li>
    	<li><%= link_to "Contact", contact_path%></li>
		<% if logged_in? %>
		<li><%= link_to "Add", create_path%></li>
		<li><%= link_to "Feed", feed_path%></li>
		<li><%= link_to "logout", logout_path%></li>
		<%end%>
	<ul>
	</div>
</div>
<div class="container" id="content">
  <% if flash.notice %><div class="alert alert-success" data-dismiss="alert"><%= flash.notice %><a class="close" data-dismiss="alert" href="#">&times;</a></div><% end %>
  <% if flash.alert  %><div class="alert alert-error" data-dismiss="alert" ><%= flash.alert  %><a class="close" data-dismiss="alert" href="#">&times;</a></div><% end %>
<%= yield %>
</div>
<div class="container">
<footer class='span12'>&copy; Lukundu Lako 2012</footer>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h2><small>About</small> <strong>me</strong></h2>
<div class="line"></div>
<p>
	<strong>"Captured by my own creativity"</strong>
</p>
<p>
	 Not much for explanation, but if you must know. I'm a twenty year old student, out of Ottawa. I just want to share my collection of photos. I take too many pictures, but what is too many. I hope you enjoy.
</p>
<br/>
<p>	
	Cheers,
</p>
<p>	
	Lukundu Lako. 
</p>

app/views/pages/create.html.erb
<h2><small>Contact<small> <strong>Moi</strong></h2>
<div class="line"></div>
<br/>
<div class="span7">
<%= form_for @message, :url => contact_path  do |form|  %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.label 'email address' %><br />
  <%= form.text_field :email, :size => 60 %><br />
  <%= form.label :subject %><br />
  <%= form.text_field :subject, :size => 60 %><br />
  <%= form.label :body %>
  <%= form.text_area :body, :class => "textarea" , :placeholder => "Enter message..." %>
	<br/>
  <%= form.submit "Send"%>

<% end %>

</div>

app/views/pages/new.html.erb
<h2><small>Contact</small> <strong>Moi</strong></h2>
<div class="line"></div>
<div id='msg'>
<br/>
<h4><strong>"</strong><small>Send me your email,</small> <strong>I just might answer." </strong></h4>
</div>
<br/>
  <div class="span7">
<%= form_for @message, :url => contact_path  do |form|  %>
  <%= form.label :name %>
  <%= form.text_field :name, :placeholder => "Mister Love" %>
  <%= form.label 'email address' %><br />
  <%= form.text_field :email, :size => 60, :placeholder => "you@me.com" %><br />
  <%= form.label :subject %>
  <%= form.text_field :subject, :size => 60, :placeholder => "hello good sir!" %><br />
  <%= form.label 'Your message' %>
  <%= form.text_area :body, :class => "textarea" , :placeholder => "Enter message..." %>
	<br/>
  <%= form.submit "Send"%>

<% end %>

</div>

app/views/posts/create.html.erb
  <div class="span7">
<%= form_for @post, :html => { :multipart => true } do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label "Description" %>
  <%= form.text_area :desc, :class => "textarea" , :placeholder => "Enter description..." %>
  <span class="btn btn-success fileinput-button">
  <%= form.file_field :img%>
	</span>
	<br/>
	<br/>
  <%= form.submit "Post"%>

<% end %>

</div>

app/views/posts/edit.html.erb
  <div class="span6">
<%= form_for @post, :html => {:multipart => true} do |form| %>
  <%= image_tag @post.img.url(:medium) %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label "Description" %>
  <%= form.text_area :desc, :class => "textarea" , :placeholder => "Enter description..." %>
	<br/>
	<br/>
  <%= form.submit "Update"%>

<% end %>

</div>

app/views/posts/feed.html.erb
  

<table class="table">
	<tr>
		<td>Id</td>
		<td>Title</td>
		<td>Image</td>
		<td>Delete</td>
		<td>Edit</td>
	<tr>
<% @post.each do |n| %>
		<td><%= n.id %></td>
    	<td><%= n.title %></td>
    	<td><%= image_tag n.img.url(:thumb) %></td>
    	<td><%= link_to 'Delete', n, :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?'} %></td>
		<td><%= link_to 'Edit', edit_post_path(:id =>n),:class => 'btn btn-warning'%></td>
  	</tr>
<% end %>
 </table>

app/views/posts/index.html.erb
<div id="news" class="span3 " >
	<h2>Welcome</h2>
	<div class="line2"></div>
	<br/>
	<p> Here's a collection of my photos</p>
</div>

<div id="feed" class="span6 offset2 ">
<div id="title-head">
	<h2>My Photos</h2>
	<div class="line"></div>
</div>
<div id="qview"></div>
 <div id="photos">
	<% @post.each do |n| %>
	<div class="title">
	<h4><strong><%= truncate(n.title,:length =>20) %></strong><small> <%=time_ago_in_words(n.created_at)%></small></h4>
	</div>
 	<div class="posts">
	<%= link_to (image_tag n.img.url(:medium),:class => "img-polaroid"),n,:controller => 'posts' %> 
	<%= truncate(n.desc , :length => 30, :omission => '...continued') %>
	</div>
	<br/>
	<% end %>
 </div>
</div>

app/views/posts/show.html.erb
<div class="span10 offset1">
<table class="post">
    <h2><%= @post.title %></h2>
	<br/>
	<tr>
	<td><%= image_tag @post.img.url(:large) %></td>
	</tr>
	<tr>
	<td><%= @post.desc %></td>
	</tr>
</table>
</div>